---
title: Prerequisites
weight: 20
---
== Prerequisites to install OpenServerless

This page lists the prerequisites to install OpenServerless in various environments.

You can install OpenServerless:

* for **development** in a <<single-node, single node>> environment, either in your local machine or in a Linux server.
* for **production**, in a <<multi-node, multi node>> environment provided by a Kubernetes cluster.

[#single-node]
== Single Node development installation

For **development** purposes, you can install a single node OpenServerless deployment in the following environments as soon as the following requirements are satisfied:

* To install in your xref:install-local.adoc[local machine], you need xref:prereq-docker.adoc[Docker Desktop] 
* To install in a *single node* xref:install-server.adoc[Linux server],  you need a server with xref:prereq-server.adoc[passwordless ssh access and sudo].

Our installer can automatically install a Kubernetes environment, using https://k3s.io[K3S], but if you prefer you can install a single-node Kubernetes instance by yourself.

If you choose to install Kubernetes on your server, we provide support for:

* xref:prereq-k3s.adoc[SuSE K3S] 
* xref:prereq-mk8s.adoc[Canonical MicroK8S]

[#multi-node]
== Multi Node production installation

For **production** purposes, you need a multi-node Kubernetes cluster that satisfies xref:kubernetes/index.adoc[those requirements], accessible with its `kubeconfig` file.

If you have such a cluster, you can  install  xref:../install/cluster/index.adoc[OpenServerless in a Kubernetes cluster]

If you do not have a cluster and you need to setup one, we provide support for provisioning a suitable cluster that satisfied our requirements for the following Kubernetes environments:

* xref:kubernetes/eks/index.adoc[EKS in Amazon AWS] 
* xref:kubernetes/aks/index.adoc[AKS in Microsoft Azure]
* xref:kubernetes/gke/index.adoc[GKE in Google Cloud]
* xref:kubernetes/openshift/index.adoc[RedHat OpenShift] 

Once you have a suitable Kubernetes cluster, you can proceed xref:install.adoc[installing OpenServerless].