---
title: Install K3S
---
== Install K3S in a server

You can install OpenServerless as xref:../../../install/server/index.adoc[described here], and you do not need to install any Kubernetes in it, as it is installed as part of the procedure. In this case it installs https://k3s.io[K3S].

Or you can <<installing-k3s, install K3S in advance>>, and then proceed xref:../../../configure/index.adoc[configuring] and then installing OpenServerless xref:../../../install/cluster/index.adoc[as in any other Kubernetes cluster].

[#installing-k3s]
== Installing K3S in a server

Before installing ensure you have xref:../../../prereq/index.adoc[satified the prerequisites], most notably:

. you know the **IP address or DNS name**
. your server operating system satisfies the https://docs.k3s.io/installation/requirements[K3S requirements]
. you have passwordless access with ssh
. you have a user with passwordless sudo rights
. you have opened the port 6443 in the firewall

Then you can use the following subcommand to install in the server:

[source,bash]
----
ops cloud k3s create SERVER=<server> USERNAME=<username>
----

where `<server>` is the **IP address or DNS name** to access the server, and `<username>` is the user you use to access the server.

Those pieces of information should have been provided when provisioning the server.

[IMPORTANT]
====
If you installed a Kubernetes cluster in the server this way, you should proceed installing OpenServerless as in xref:../../../install/cluster/index.adoc[a Kubernetes cluster], **not** as a server.
====

The installation retrieves also a Kubernetes configuration file, so you can proceed to installing it without any other step involved.

== Additional Commands

In addition to `create` the following subcommands are also available:

* `ops cloud k3s delete SERVER=<server> USERNAME=<username>`: uninstall K3S from the server
* `ops cloud k3s kubeconfig SERVER=<server> USERNAME=<username>`: retrieve the kubeconfig from the K3S server
* `ops cloud k3s info`: some information about the server
* `ops cloud k3s status`: status of the server

